server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - regex:
      expression: "(?.*)"

  # # Docker container logs
  # - job_name: docker
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock

  #   relabel_configs:
  #     # Add container name and image as labels
  #     - source_labels: [__meta_docker_container_name]
  #       target_label: container
  #     - source_labels: [__meta_docker_container_image]
  #       target_label: image

  #   pipeline_stages:
  #     - json:
  #         expressions:
  #           log: log
  #           stream: stream
  #           time: time
  #     - logfmt:
  #         mapping:
  #           level: level
  #           caller: caller
  #           msg: msg
  #           name: name
  #           op: op
  #     - labels:
  #         level:
  #         caller:
  #         op:
  #     - timestamp:
  #         source: time
  #         format: RFC3339Nano
  #     - output:
  #         source: msg

  # # System logs
  # - job_name: syslog
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: syslog
  #         __path__: /var/log/syslog

  # # Application-specific logs
  # - job_name: supabase
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: supabase
  #         __path__: /var/log/supabase/*.log
