apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: supabase-db:5432
    database: postgres
    user: supabase_admin
    password: ${SUPABASE_DB_PASSWORD}
    sslmode: disable
    editable: true